# Generated by Django 4.2.6 on 2023-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='country_name',
        ),
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='india@gmail.com', max_length=254),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='States',
        ),
    ]
